added authorization and go to other activity
AlexM-pixel/MedicalTests pull request #1
Opened 2020-04-10 11:20 UTC by AlexM-pixel

2020-04-10 11:26 UTC, AlexM-pixel commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +    private boolean validateForm() {                                                                //  доделать валидацию
Потом сделаю нормальную валидацию в отдельном классе

2020-04-10 11:29 UTC, AlexM-pixel commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +            startActivityForResult(intent, 1);
startActivityForResult использовал чтобы не возвращало назад в это активити если пользователь уже авторизован

2020-04-13 07:52 UTC, AinisSK requested changes

2020-04-13 07:52 UTC, AinisSK commented on .gitignore
> +.idea
Тут наверное нужен в начале /
потому что у тебя все равно файлы из папки есть в пул реквесте

2020-04-13 07:52 UTC, AinisSK commented on app/src/main/AndroidManifest.xml
> +            >
Такие теги если они без тела можно сразу закрывать
Например <activity .... />

2020-04-13 07:52 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +    void updateUI(FirebaseUser user) {
У тебя везде по коду перед выходом этого метода берется текущий пользователь: mAuth.getUser. По идее это обязательный шаг, тогда его нельзя выполнять отдельно, потому что если кто-то захочет обновить в последствии юай, надо делать дополнительные операции. Я бы закинул в этот метод получение пользователя

2020-04-13 07:52 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +            Intent intent = new Intent(MainActivity.this, SpisokActivity.class);
Если это не вложенный класс используй просто this, так как это и будет Активити

2020-04-13 07:52 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/SpisokActivity.java
> +        setResult(RESULT_OK);
Зачем тут проставляется результат?

2020-04-13 07:52 UTC, AinisSK commented on app/src/main/res/layout/activity_spisok.xml
> +        android:text="Выйти из аккаунта"
Атата

2020-04-29 13:42 UTC, AinisSK requested changes

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/SpisokActivity.java
> +        setResult(RESULT_OK);
Перенести в OnBackPressed() метод

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/validation/Validation.java
> +    public boolean validEmail(String mail, EditText editMail) {
Валидация емэйла неправильная, вот такой емэйл не проходит: ainis.timyo@gmail.com

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +    FragmentManager fm;
Незачем сохранять его в переменную, он и так тебе доступен во всем классе

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +    LinearLayout show_menu;
showMenuLayout, если бы это была кнопка то showMenuBtn, если просто view то showMenuView. В классах переменные должны быть всегда кэмел кейсом

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +    EditText fragmentEmail;
Что означает у этих эдиттекстов префикс fragment?

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +    int count = 0;
И тут много чего должно быть приватным

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +    ProgressBar ProgressBar;
с маленькой буквы должно начинаться

2020-04-29 13:42 UTC, AinisSK commented on app/src/main/res/layout/dialog_email.xml
> +        <requestFocus />
Зачем вот это вот тут?

2020-05-14 13:34 UTC, AlexM-pixel commented on app/src/main/java/com/example/medicaltests/SpisokActivity.java
> +        setResult(RESULT_OK);
Почему тут весит этот коммент если у меня и класса такого уже нету давно, я каждый раз ищу  его переделать)

2020-05-21 13:47 UTC, AinisSK requested changes
Надо старые и новые коменты поправить

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/Activity2Main.java
> +            fr = getSupportFragmentManager();
Нет смысла выносить это в глобальные переменные

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/AuthFragment.java
> +                sex = (isChecked ? "женский" : "мужской");
Это тоже должно быть в strings.xml

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/MainActivity.java
> +        if (email.equals("")) {
TextUtils.isEmpty

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/all_analysis/SpisokFragment.java
> +    public ArrayList<AnalysCardView> cardViewArrayList;
Тут нам не надо хранить список объектов. Он нужен только в адаптере

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/all_analysis/SpisokFragment.java
> +        adapter = new AnalysisAdapter(cardViewArrayList);
Вот ты его передаешь в адаптер и все, глобально в переменную не надо записывать

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/java/com/example/medicaltests/saveAtateSQLite/DatabaseHelper.java
> +        insertAnalys(db, "Общий анализ крови", R.drawable.true_blood);
Про это уже обсуждали, тогда поправь обязательно

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/res/layout/activity_main.xml
> +    <FrameLayout
FrameLayout LinearLayout смотрятся костылями в constraintLayout

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/res/layout/activity_spisok.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Вот тут использования RelativeLayout оправданно

2020-05-21 13:47 UTC, AinisSK commented on app/src/main/res/layout/activity_spisok.xml
> +    android:orientation="vertical"
Только orientation у него нет

2020-05-21 14:58 UTC, closed without merging